services:
  - type: web
    name: telegram-card-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 8103948431:AAEZgtxTZPA1tvuo8Lc6iA5-UZ7RFiqSzhs
    plan: free
    autoDeploy: true
